some functions
fipl-hse/2020-2-level-labs pull request #129
Opened 2020-10-22 08:10 UTC by MilanaShhanukova

2020-10-22 08:13 UTC, WhiteJaeger commented
Please rename using the template so we can see whose PR this is.

2020-10-22 13:36 UTC, WhiteJaeger requested changes

2020-10-22 13:36 UTC, WhiteJaeger commented on lab_2/main.py
> -def tokenize_by_lines(text: str) -> tuple:
This function is needed in tests and for working with big files.

2020-10-22 13:36 UTC, WhiteJaeger commented on lab_2/main.py
> +def checker(object_to_check, expected_type):
Functions usually have verb-like names:
Like `check_object_type`

2020-10-22 13:36 UTC, WhiteJaeger commented on lab_2/main.py
> +        return -1
These checks can be shortened, like `not object` or `not len(object)`.

2020-10-22 13:36 UTC, WhiteJaeger commented on lab_2/main.py
> +    if lcs_length == 0:
`lcs_length == 0` can be shortened.

2020-10-22 13:36 UTC, WhiteJaeger commented on lab_2/main.py
> +    for l in range(len(original_text_tokens)):
`l` is not very descriptive name, right?

2020-10-22 13:36 UTC, WhiteJaeger commented on lab_2/main.py
> +    def count_difference(tokens):
It is better not to nest functions. I suggest moving it outside and using it like utility function here.

2020-10-22 13:36 UTC, WhiteJaeger commented on lab_2/main.py
> -def tokenize_big_file(path_to_file: str) -> tuple:
Please, leave function descriptions as they are.

2020-10-23 06:23 UTC, WhiteJaeger requested changes

2020-10-23 06:23 UTC, WhiteJaeger commented on lab_2/find_lenght_test.py
> +# pylint: skip-file
What is this file?

2020-10-23 06:23 UTC, WhiteJaeger commented on lab_2/main.py
> +    tokenized_text = [sent for sent in tokenized_text if sent != ()]
`if sent != ()` can be shortened.

2020-10-23 06:23 UTC, WhiteJaeger commented on lab_2/main.py
> +    :param second_sentence_tokens: a list of tokens
Please, leave function descriptions as they are.

2020-10-23 06:23 UTC, WhiteJaeger commented on lab_2/main.py
> +    with open("data.txt") as first_file, open("data_2.txt") as second_file:
You do need to open these particular files. 
You should work with `path_to_file` argument.

2020-10-28 15:55 UTC, WhiteJaeger commented on lab_2/main.py
> +        second_lines = (tokenize_by_lines(line_2) for line_2 in second_file)
Why do you open the same file twice?

2020-10-28 15:55 UTC, WhiteJaeger commented on lab_2/main.py
> +                   for first_line, second_line in zip(first_lines, second_lines))
These would be identical files, right?

2020-10-29 18:11 UTC, MilanaShhanukova commented on lab_2/main.py
> +        second_lines = (tokenize_by_lines(line_2) for line_2 in second_file)
i've changed this already

2020-10-29 18:11 UTC, MilanaShhanukova commented on lab_2/main.py
> +                   for first_line, second_line in zip(first_lines, second_lines))
i've changed this already

2020-11-01 16:46 UTC, closed without merging