'Laboratory work #1, Shuvar Alena - 19FPL2'
fipl-hse/2020-2-level-labs pull request #30
Opened 2020-09-17 19:49 UTC by alenashuvar

2020-09-22 17:36 UTC, WhiteJaeger commented
The deadline is not that far - consider pushing changes so that we can review them.

2020-09-27 20:08 UTC, WhiteJaeger requested changes

2020-09-27 20:08 UTC, WhiteJaeger commented on lab_1/main.py
> +    if type(text) != str:
`type` is usually considered a bad style, look for smth else.

2020-09-27 20:08 UTC, WhiteJaeger commented on lab_1/main.py
> +    text = text.lower()
Usually it is better to create a separate variable to work with it and leave input as it is.

2020-09-27 20:08 UTC, WhiteJaeger commented on lab_1/main.py
> +    elif type(stop_words) != list:
Please, try to shorten the checks.

2020-09-27 20:08 UTC, WhiteJaeger commented on lab_1/main.py
> +    else:
You can get rid of this `else`-block.

2020-09-27 20:08 UTC, WhiteJaeger commented on lab_1/main.py
> +            if (type(left_context_size) != int) or (left_context_size < 1):
Checks better to be placed somewhere in the beginning of the function.

2020-09-27 20:08 UTC, WhiteJaeger commented on lab_1/main.py
> +    with open(path_to_file, 'r', encoding='utf-8') as file:
It is usually considered a bad style (and a dangerous one!) to use built-in words (e.g. `str`, `list` etc.) as variable names.

2020-09-27 20:08 UTC, WhiteJaeger commented on lab_1/main.py
> +    name_file = path_to_file + 'report.txt'
Path to file is passed as the following:
`path/to/file.txt` -> no need for this line.

2020-09-27 21:24 UTC, alenashuvar commented on lab_1/main.py
> +    elif type(stop_words) != list:
I don't know how :(

2020-09-29 16:10 UTC, WhiteJaeger commented on lab_1/main.py
> +    if not isinstance(text, str):
Nice.

2020-09-29 16:13 UTC, WhiteJaeger commented
Great work! You are done here.

2020-09-29 16:13 UTC, WhiteJaeger approved these changes
Great work! You are done here.

2020-10-14 09:10 UTC, WhiteJaeger commented
Open another PR with lab_2.

2020-10-14 09:10 UTC, closed without merging