dev: start_test
fipl-hse/2020-2-level-labs pull request #58
Opened 2020-09-23 15:41 UTC by dmitry-uraev

2020-09-23 16:06 UTC, WhiteJaeger commented on config/start_py_test.py
> +    if expected == actual or expected in content:
`expected` is a string and `actual` is a list, so they cannot be equal.

2020-09-23 16:06 UTC, WhiteJaeger commented on config/start_py_test.py
> +    if result == 1:
result is either 0 or 1, so better would be:
```suggestion
    if result:
```

2020-09-23 16:06 UTC, WhiteJaeger commented on config/start_py_test.py
> +# pylint: skip-file
I do not really understand this test. It checks for the line that is already in `start.py` file, so this test will pass - why do we need it then?

2020-09-23 16:45 UTC, demid5111 requested changes

2020-09-23 16:45 UTC, demid5111 commented on config/start_py_test.py
> +# pylint: skip-file
do not skip this file from lint

2020-09-23 16:45 UTC, demid5111 commented on config/start_py_test.py
> +import argparse
rename to reflect content - it is not a test, it is a check script, check_start_content

2020-09-23 16:45 UTC, demid5111 commented on config/start_py_test.py
> +def check_assert_is_in_file(content: str):
is_assert_in_file() -> bool

2020-09-23 16:45 UTC, demid5111 commented on config/start_py_test.py
> +    if expected == actual or expected in content:
return condition directly

2020-09-23 16:45 UTC, demid5111 commented on config/run-start.sh
> +    	WAS_FAILED=1
formatting

2020-09-24 05:41 UTC, WhiteJaeger requested changes

2020-09-24 05:41 UTC, WhiteJaeger commented on config/check_start_content.py
> +        return True
You do need need extra line, just return the result of the condition.

2020-09-24 05:41 UTC, WhiteJaeger commented on config/check_start_content.py
> +def check_assert_is_in_file(content: str):
Please, specify return type and use shorter name.

2020-09-24 16:55 UTC, merged